version: "3.9"

services:
  database:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_UNSAFE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_UNSAFE_PASSWORD}
      POSTGRES_DB: prdb
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data
    networks:
    - back-end

volumes:
 db_data:

networks:
  back-end:
    driver: bridge