app:
  name: "pull request assigning reviewers"
  appversion: "1.0.0"

database:
  name: "prdb"
  port: 5432
  sslmode: "disable"
  schema: "public"
  maxpoolsize: 7
  max_conn_lifetime: 300s
  max_connect_timeout: 500ms
  query_timeout: 250ms

server:
  read_timeout: 500ms
  write_timeout: 400ms
  shutdown_timeout: 100000s
  addr: "0.0.0.0:8080"
