app:
  name: "pull request assigning reviewers"
  appversion: "1.0.0"

database:
  name: "prdb"
  port: 5433
  sslmode: "disable"
  schema: "public"
  maxpoolsize: 10

server:
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 600000s
  addr: "0.0.0.0:8080"
